services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: task-manager-app
    working_dir: /app
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - '3000:3000'
    environment:
      - NODE_ENV=development
      - MONGO_URI=${MONGO_URI}
      - REDIS_URL=${REDIS_URL}
    depends_on:
      - mongo

volumes:
  redis-data:
